### ISSUE TITLE
nogc related compilation error

### ISSUE THREAD

**Issue by BlackEdder** [Hackerpilot/dfmt#13] opened 2015-02-16 12:39 UTC
I get the following error after the latest commit:
```
• dub
libdparse: ["libdparse"]
dfmt: ["dfmt", "libdparse"]
Target is up to date. Using existing build in /home/edwin/.dub/packages/libdparse-master/.dub/build/library-debug-linux.posix-x86_64-dmd-E198791B6673AEAE0964E351E0B4BB0A/. Use --force to force a rebuild.
Building dfmt configuration "application", build type debug.
Compiling...
src/dfmt.d(499): Error: @nogc function 'dfmt.TokenFormatter!(LockingTextWriter).TokenFormatter.expressionLength' cannot call non-@nogc function 'std.d.lexer.isBasicType'
src/dfmt.d(73): Error: template instance dfmt.format!(LockingTextWriter) error instantiating
src/dfmt.d(40): Error: function D main no return exp; or assert(0); at end of function
FAIL .dub/build/application-debug-linux.posix-x86_64-dmd-D80DC97764A9DF7D438DB64CB56228E4 dfmt executable
Error executing command run: DMD compile run failed with exit code 1
```

D version information:
• dmd
DMD64 D Compiler v2.066.1-devel
Copyright (c) 1999-2014 by Digital Mars written by Walter Bright
Documentation: http://dlang.org/

**Comment by Hackerpilot** [comment] 2015-04-20 16:49
dfmt builds successfully for me with dmd and ldc. Can you confirm that you're still having build problems?

**Comment by BlackEdder** [comment] 2015-04-21 09:34
I now seem to get the following different error (still on 2.066.1). It might be interesting to get travis CI integrated to test the builds automatically. I'd be happy to submit a pull request with a travis file for that purpose.

```
 dfmt dub
WARNING: A deprecated branch based version specification is used for the dependency libdparse. Please use numbered versions instead. Also note that you can still use the dub.selections.json file to override a certain dependency to use a branch instead.
Target libdparse ~master is up to date. Use --force to rebuild.
Building dfmt 0.2.2 configuration "application", build type debug.
Compiling using dmd...
src/dfmt/formatter.d(1373): Error: @nogc function 'dfmt.formatter.canFindIndex' cannot call non-@nogc function 'std.range.assumeSorted!("a < b", const(ulong)[]).assumeSorted'
FAIL .dub/build/application-debug-linux.posix-x86_64-dmd_2066-6D71006389B3841AD8C75F8D43E64D44/ dfmt executable
Error executing command run: dmd failed with exit code 1.
```

**Comment by Hackerpilot** [comment] 2015-04-21 10:10
https://travis-ci.org/Hackerpilot/dfmt/builds

I even have the build status badge on the project's front page...

**Comment by BlackEdder** [comment] 2015-04-21 11:32
Sorry, am currently cursed with very slow network, so didn't take the time
to double check the front page :(

If it works on travis it should be fine for me (I am on linux as well).
Will try to hunt it down myself and report back.

**Comment by yannick** [comment] 2015-04-28 09:25
for me using
```dub build -b release --combined```  made it work

**Comment by yebblies** [comment] 2015-05-17 09:30
The problem is that `SortedRange.this` is not nogc in `-debug` mode.

Because it calls `dbgVerifySorted` which calls `uniform` which is not nogc.

It may be worth removing the `@nogc` annotation from dfmt until this is fixed.

**Comment by dmi7ry** [comment] 2015-07-01 08:59
@yannick thanks, it helps.

**Comment by Hackerpilot** [comment] 2015-10-29 23:59
I'm going to close this because the code works for me (and the CI system).

**Closed by Hackerpilot** 2015-10-29 23:59 UTC
