### ISSUE TITLE
Configure formatting via settings file

### ISSUE THREAD

**Issue by mihails-strasuns-sociomantic** [Hackerpilot/dfmt#84] opened 2015-03-10 01:56 UTC
Currently dfmt provides few options that affect formatting style as CLI flags. In the long term it would be desirable to have all of those stored in a single configuration file (similar to `codestyle.xml` in Eclipse) to make it easier to ensure everyone in the team uses same style setup.

And, of course, much more configurable options are needed.

(low-priority, I will look into it myself once start integrating dfmt in our internal code base)

**Comment by Hackerpilot** [comment] 2015-03-10 03:03
Duplicate of https://github.com/Hackerpilot/dfmt/issues/75

**Closed by Hackerpilot** 2015-03-10 03:03 UTC
Labels: duplicate

**Comment by Hackerpilot** [comment] 2015-03-10 03:04
I feel I should warn you that I'm making no effort to support D1 at all.

**Comment by mihails-strasuns-sociomantic** [comment] 2015-03-10 03:06
Oops, sorry, was searching through issue titles for the keyword "file".

> I feel I should warn you that I'm making no effort to support D1 at all.

Was referring to our D2 code which looks totally real now :P
