### ISSUE TITLE
'else' gets wrong indentation when 'if' is labelled

### ISSUE THREAD

**Issue by yebblies** [Hackerpilot/dfmt#168] opened 2015-08-07 00:17 UTC
```diff
unittest
{
    if (0)
    {
    L1:
        if (Port.isNan(r1) || Port.isNan(r2)) // if unordered
        {
            return 1;
        }
-        else
+    else
        {
            return (r1 != r2);
        }
    }
}
```

**Comment by Hackerpilot** [comment] 2015-08-10 23:06
This is a duplicate of #169. The label isn't the problem, the comment at the end of the line with the `if` is the problem. Closing because I can't reproduce the problem now that #169 is fixed.

**Closed by Hackerpilot** 2015-08-10 23:06 UTC
Labels: bug, indentation
